# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-20 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamedev', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='comments_count',
        ),
    ]
